# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
      - uses: actions/checkout@v2    
      
      - name: Run if not in nehas repo
        if: github.repository != 'Neha-Sinha2305/repo-for-github-actions'
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Run if in nehas repo
        if: github.repository == 'Neha-Sinha2305/repo-for-github-actions'
      - name: Run a one-line script neha
        run: echo Hello, neha!
      - name: Run a multi-line script neha
        run: |
          echo Add other actions to build neha,
          echo test, and deploy your project.
