# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, edited, closed]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#  enforce-changelog:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: dangoslen/changelog-enforcer@v1.1.1
#        with:
#          changeLogPath: 'CHANGELOG.md'
#          skipLabel: 'test-skipping-changelog'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # This workflow containss a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Test labels
        env:
          LABELS1: ${{ toJson(github.event.pull_request.labels.*.name) }}
        run: echo "$LABELS1"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.