# This is a basic workflow to help you get started with Actions
#replace: "'\\''"
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
    types:
      - edited
      - synchronized
      - opened

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Find and replace
        run: python .github/action/find-replace.py
        env:
          find: "'"
          replace: "'\\''"
          FILE_NAME: CHANGELOG.md

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1.1.0
        with:
          path: CHANGELOG.md

      - name: Echo package.json
        run: echo '${{ steps.changelog_reader.outputs.log_entry }}'




      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
