# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
      - uses: actions/checkout@v2    
      - uses: maxkomarychev/oction-create-issue@v0.7.1
        id: my_step_id
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update minio module to the latest release++"
          body: "Update minio- module in the following repo: https://github.com/fredrikhgrelland/terraform-nomad-presto"
      - name: Print outputs
        run: |
            echo ${{ steps.my_step_id.outputs.id }}
            echo ${{ steps.my_step_id.outputs.number }}
